### ISSUE TITLE
获取登录二维码失败

### ISSUE THREAD

**Issue by tonight-love** [icecooly/WeixinAutoChat#2]
二维码获取失败了

**Comment by icecooly** [comment]
我刚试了 可以的啊  macos  你是什么环境？

**Comment by huage201201** [comment]
我也遇到这个问题了,打印了下错误信息是因为路径未找到导致的,可以在Config中修改下路径

**Comment by tom0gao** [comment]
怎么修改路径？

**Comment by tom0gao** [comment]
BufferedImage image = ImageIO.read(new File(qrPath)); 
提示这句话报错
Caught and handled this exception :
java.lang.NumberFormatException: For input string: ""

**Comment by tom0gao** [comment]
String rspMsg=null;
		String url=API_URL+"/cgi-bin/mmwebwx-bin/login";
		long now=System.currentTimeMillis();
		rspMsg=httpClient.get().
				url(url).
				addParams("uuid",uuid).
				addParams("tip", tip).
				addParams("loginicon", "true").
				addParams("R",getR()).
				addParams("_", String.valueOf(now)).
				build().
				execute().
				string();
		//
		if(rspMsg.indexOf("window.code=200")!=-1){//success   这里一直400

**Comment by icecooly** [comment]
我这里可以  会不会是你的网络问题？

**Comment by icecooly** [comment]
qrPath 你修改一下 比如Config.qrCodePath="c:/"
